services:
  - type: web
    name: solana-webhook
    runtime: python
    buildCommand: "pip install -r solana_webhook/requirements.txt"
    startCommand: "uvicorn solana_webhook.main:app --host 0.0.0.0 --port 8000"
    plan: free
    region: oregon
